spring:
  application:
    name: spring-today-service
  jmx:
    enabled: true

server:
  port: 7777

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true

management:
  endpoints:
    web:
      exposure:
        include: "*"