logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG

server:
  port: 9999

eureka:
  client:
    serviceUrl:
      defaultZone: http://eurekaservice:8761/eureka
      #defaultZone: ${EUREKA_URI:http://localhost:8761/eureka} #sin docker
  instance:
    preferIpAddress: true

#Ejercicio: añadimos filtrado de rutas para permitir sólo salida en Json
spring:
  application:
    name: spring-today-gateway
  cloud:
    gateway:
      httpclient: #fijamos timeout
        connect-timeout: 2000
        response-timeout: 2s
      routes:
      - id: path_today_simple #Redirección
        predicates:
        - Path=/v1/**
        # Múltiples filtros para añadir/modificar cabeceras, rewrite Path, etc
        filters:
        - RedirectTo=302, lb://spring-fail-service/v1/fail #Format: HTTP Status 302 (Redirect) / newLocation
        uri: lb://spring-fail-service/v1/fail

      - id: path_json_parameterized #Fijamos status forbidden en esta ruta
        predicates:
        - Path=/v1/todayJsonParameterized
        filters:
        - SetStatus=403
        #uri: http://gatewayservice:9999

      - id: retry_test #Intentos de reconectar (finalmente devuelve el 502 a front)
        uri: http://gatewayservice:9999 #destino
        predicates:
        - Path=/v1/badGatewayTest
        filters:
        - RedirectTo=302, http://zuulservice:8762/v1/badGatewayTest
        - name: Retry
          args:
            retries: 3
            statuses: BAD_GATEWAY
            methods: GET,POST
            backoff:
              firstBackoff: 10ms
              maxBackoff: 50ms
              factor: 2
              basedOnPreviousValue: false
