version: '2'
services:
  springbootdocker:
    build: ./
    image: spring-boot-training
    container_name: springboottrainingdocker
    restart: "no"
    ports:
      - "7777:8090"
    environment:
      - "JAVA_OPTS=-Xms128m -Xmx512m -server"
    mem_limit: 512000000
    logging:
      driver: "json-file"
      options:
        max-size: "100k"
        max-file: "10"

