FROM openjdk:8-jre-alpine

ADD ["build/libs/spring-boot-one-to-many-0.0.1-SNAPSHOT.jar", "/opt/spring-boot-one-to-many/"]

ENTRYPOINT ["java", "-jar", "/opt/spring-boot-one-to-many/spring-boot-one-to-many-0.0.1-SNAPSHOT.jar"]

EXPOSE 7777