spring:
  application:
    name: spring-today-service
  jmx:
    enabled: true

server:
  port: 7777

eureka:
  client:
    serviceUrl:
      defaultZone: http://eurekaservice:8761/eureka  #docker service
  instance:
    preferIpAddress: true

management:
  endpoints:
    web:
      exposure:
        include: "*"