spring:
  application:
    name: spring-cloud-eureka-client
  jmx:
    enabled: true

server:
  port: 8084 #cambiar en ejemplo a 8082 y 8083 para nuevas instancias

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true

management:
  endpoints:
    web:
      exposure:
        include: "*"